services:
  db:
    image: "postgres:15-alpine"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  queue:
    image: "redis:7-alpine"
    expose:
      - "6379"

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - .env
    depends_on:
      - queue
      - db

  worker:
    build: ./worker
    volumes:
      - ./worker:/app
    privileged: true
    env_file:
      - .env
    depends_on:
      - queue
      - db