"""Create initial database schema

Revision ID: 4b5a76bbab53
Revises: 
Create Date: 2025-10-16 04:28:08.512063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b5a76bbab53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_extension', sa.Text(), nullable=False),
    sa.Column('compile_command', sa.Text(), nullable=True),
    sa.Column('run_command', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('compile_output', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'FINISHED', 'ERROR', name='submissionstatus'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('cpu_time_limit', sa.Float(), nullable=True),
    sa.Column('cpu_extra_time', sa.Float(), nullable=True),
    sa.Column('wall_time_limit', sa.Float(), nullable=True),
    sa.Column('memory_limit', sa.Integer(), nullable=True),
    sa.Column('max_processes_and_or_threads', sa.Integer(), nullable=True),
    sa.Column('max_file_size', sa.Integer(), nullable=True),
    sa.Column('number_of_runs', sa.Integer(), nullable=True),
    sa.Column('enable_per_process_and_thread_time_limit', sa.Boolean(), nullable=True),
    sa.Column('enable_per_process_and_thread_memory_limit', sa.Boolean(), nullable=True),
    sa.Column('redirect_stderr_to_stdout', sa.Boolean(), nullable=True),
    sa.Column('enable_network', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
